### ISSUE TITLE
墙烈建议加一个一键保存图片或右键新标签打开

### ISSUE THREAD

**Issue by ChenYFan** [nidbCN/novelai-sample#1]
图片不能右键保存是什么魔鬼行为。。。

**Comment by nidbCN** [comment]
原因是 vuetify 的组件使用一个 div 和 `background-image` CSS 来展现图片。
等下改成直接使用原生 HTML 的  `img` 标签。

**Comment by nidbCN** [comment]
https://github.com/nidbCN/novelai-sample/commit/99674be18eb17dade07b58196e5c36dbb38ad140
